/**
 * Doctor Alert Review Panel (React)
 *
 * Allows doctors to mark alerts as reviewed/resolved/escalated.
 * Stores state in the browser session (in-memory) as allowed by spec.
 */

import { useMemo, useState } from 'react';
import DashboardCard from './DashboardCard';

function formatTime(isoOrString) {
    if (!isoOrString) return '—';
    try {
        return new Date(isoOrString).toLocaleTimeString();
    } catch {
        return String(isoOrString);
    }
}

function levelMeta(level) {
    const l = String(level || 'Warning');
    if (l === 'Critical') return { badge: 'bg-danger', icon: '🚨' };
    if (l === 'High Risk') return { badge: 'bg-warning text-dark', icon: '⚠️' };
    return { badge: 'bg-secondary', icon: '📌' };
}

function simpleHash(str) {
    let h = 0;
    for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
    return h.toString(16);
}

function buildAlertId({ patientId, message, timestamp }) {
    return `${patientId}-${simpleHash(`${message}|${timestamp}`)}`;
}

function normalizeAlerts({ patients, allPatientsData, doctorMetricsByPatientId }) {
    const items = [];

    for (const p of patients || []) {
        const d = allPatientsData?.[p.id];
        if (!d) continue;

        const metrics = doctorMetricsByPatientId?.[p.id] || null;
        const earlyRisk = Boolean(metrics?.earlyRisk);

        // Existing alerts generated by sim/backend.
        for (const msg of d.alerts || []) {
            const level = d.status === 'critical' ? 'Critical' : (d.status === 'warning' ? 'High Risk' : 'Warning');
            items.push({
                id: buildAlertId({ patientId: p.id, message: msg, timestamp: d.timestamp }),
                patientId: p.id,
                patientName: p.name,
                message: msg,
                level,
                timestamp: d.timestamp,
            });
        }

        // Dashboard-only early warning.
        if (earlyRisk && (metrics?.earlySignals?.length || 0) > 0) {
            const msg = `Early warning: ${metrics.earlySignals.join(', ')}`;
            items.push({
                id: buildAlertId({ patientId: p.id, message: msg, timestamp: d.timestamp }),
                patientId: p.id,
                patientName: p.name,
                message: msg,
                level: 'Warning',
                timestamp: d.timestamp,
            });
        }
    }

    const pr = { Critical: 3, 'High Risk': 2, Warning: 1 };
    items.sort((a, b) => {
        const pa = pr[a.level] || 0;
        const pb = pr[b.level] || 0;
        if (pb !== pa) return pb - pa;
        return new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime();
    });

    return items;
}

function DoctorAlertReviewCard({ patients, allPatientsData, doctorMetricsByPatientId, onSelectPatient }) {
    const [stateById, setStateById] = useState({});

    const alerts = useMemo(() => {
        return normalizeAlerts({ patients, allPatientsData, doctorMetricsByPatientId });
    }, [patients, allPatientsData, doctorMetricsByPatientId]);

    const applyAction = (alertId, action) => {
        setStateById((prev) => ({
            ...prev,
            [alertId]: { status: action, updatedAt: new Date().toISOString() },
        }));
    };

    return (
        <DashboardCard
            icon="✅"
            title="Doctor Alert Review"
            headerRight={<span className="badge bg-info">{alerts.length} items</span>}
        >
            {alerts.length === 0 && <div className="text-muted">No alerts yet.</div>}

            <div className="space-y-3">
                {alerts.map((a) => {
                    const meta = levelMeta(a.level);
                    const state = stateById[a.id]?.status || 'new';
                    const updatedAt = stateById[a.id]?.updatedAt;

                    return (
                        <div
                            key={a.id}
                            className="p-3 rounded border"
                            style={{ background: 'var(--bg-card)', borderColor: 'var(--border-color)' }}
                        >
                            <div className="d-flex justify-content-between align-items-start" style={{ gap: '12px' }}>
                                <div style={{ minWidth: 0 }}>
                                    <div className="d-flex align-items-center gap-2 mb-1">
                                        <span aria-hidden="true">{meta.icon}</span>
                                        <button
                                            type="button"
                                            className="btn btn-link p-0 fw-semibold"
                                            style={{ color: 'var(--text-primary)', textDecoration: 'none' }}
                                            onClick={() => onSelectPatient?.(a.patientId)}
                                        >
                                            {a.patientName} ({a.patientId})
                                        </button>
                                        <span className={`badge ${meta.badge}`}>{a.level}</span>
                                        <span className="badge bg-secondary">{state}</span>
                                    </div>

                                    <div className="small" style={{ color: 'var(--text-secondary)' }}>{a.message}</div>
                                    <div className="small mt-1" style={{ color: 'var(--text-muted)' }}>
                                        {formatTime(a.timestamp)}
                                        {updatedAt ? ` • Updated: ${formatTime(updatedAt)}` : ''}
                                    </div>
                                </div>

                                <div className="d-flex flex-column" style={{ gap: '8px', flex: '0 0 auto' }}>
                                    <button type="button" className="btn btn-sm btn-outline-light" onClick={() => applyAction(a.id, 'reviewed')}>
                                        Reviewed
                                    </button>
                                    <button type="button" className="btn btn-sm btn-outline-success" onClick={() => applyAction(a.id, 'resolved')}>
                                        Resolved
                                    </button>
                                    <button type="button" className="btn btn-sm btn-outline-danger" onClick={() => applyAction(a.id, 'escalated')}>
                                        Escalate
                                    </button>
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>
        </DashboardCard>
    );
}

export default DoctorAlertReviewCard;
